# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

react_native_path = '../node_modules/react-native'

target 'hotUpdate' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for hotUpdate
  pod 'AFNetworking',             '~> 3.1.0'
  pod 'ZipArchive',               '~> 1.4.0'
  
  # Third party deps
  pod 'DoubleConversion', :podspec => react_native_path + '/third-party-podspecs/DoubleConversion.podspec'
  pod 'GLog', :podspec => react_native_path + '/third-party-podspecs/GLog.podspec'
  pod 'Folly', :podspec => react_native_path + '/third-party-podspecs/Folly.podspec'
  
  pod 'React’, :path => ‘../node_modules/react-native’, :subspecs => [
    'Core',
#    'BatchedBridge',
    'CxxBridge',
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTActionSheet',
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTAnimation',
    'RCTLinkingIOS',
    'ART',
    'jschelpers_legacy',
    'cxxreact_legacy',
    # needed for debugging
    # Add any other subspecs you want to use in your project
    ]
  # 如果你的RN版本 >= 0.42.0，则加入下面这行
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

  pod 'FegoRnUpdate', :path => ‘../../‘

  target 'hotUpdateTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
